root_dir/root/urls.py
from django.contrib import admin
from django.urls import path, include
from social.views import profile, profileChange
from imessage.views import messanger_home, messanger_create, messanger_show
urlpatterns = [
    path('', include('users.urls')),
    path('profile/<str:slug>/', profile, name="profile"),
    path('profileChange/', profileChange, name="profile-change"),
    path('imessage/', messanger_home, name="messenger"),
    path('send_imessage/', messanger_create, name="messanger_create"),
    path('chat/', messanger_show, name="messanger_create"),
    path('home/', include('social.urls'), name="home"),
    path('admin/', admin.site.urls),
]

root_dir/social/urls.py
from django.urls import path
from .views import *


app_name = 'social'
urlpatterns = [
    path('', home, name='home'),
    path('create/', create, name='create'),
    path('post/<int:pk>', show_post, name="show_post"),
    path('search/', SearchAPI, name='search'),
    path('like/', Like, name='Like-toggle'),
    path('bookmark/', create_bookmark, name='bookmark_create'),
    path('delete/<int:id>', delete, name='delete'),
    path('bookmarks/', bookmark, name='bookmark'),
]

root_dir/users/urls.py
from django.urls import path
from django.contrib import admin
from django.contrib.auth import views as auth_views
from .views import *
from .forms import CustomAuthForm
from django.conf import settings
from django.conf.urls.static import static

app_name="users"
urlpatterns = [
    path('', auth_views.LoginView.as_view(template_name="users/home.html", redirect_authenticated_user=True, authentication_form=CustomAuthForm), name="home"),
    path('register/', register, name="register"),
    path('settings/', setting, name="settings"),
    path('logout/',auth_views.LogoutView.as_view(template_name="users/logout.html"), name="logout")
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

root_dir/social/models.py
from django.db import models
from PIL import Image
from django.urls import reverse
from django.utils import timezone
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.core.files.images import get_image_dimensions
from django.contrib.humanize.templatetags import humanize


def validate_image(image):
    min_height = 590
    min_width = 590
    width, height = get_image_dimensions(image) 
    if width < min_width or height < min_height:
        raise ValidationError("Height or Width is lower than what is allowed")



class PostCreate(models.Model):
    user_name  = models.ForeignKey(User, on_delete=models.CASCADE)
    post_image = models.ImageField('image', upload_to="posts_pics", validators=[validate_image])
    date       = models.DateTimeField(default=timezone.now)
    likes      = models.ManyToManyField(User, blank=True, related_name="post_likes")

    class Meta:
        verbose_name_plural = ("Posts")

    def __str__(self):
        return f'{self.user_name} Post'

    def get_date(self):
        return humanize.naturaltime(self.date)

    def get_absolute_url(self):
        return reverse("social:home")
    
    def get_like_url(self):
        return reverse("social:Like-toggle")


    def save(self):
        super().save()
        img = Image.open(self.post_image.path)

        if img.height > 520 and img.width > 590:
            output_size = (590, 590)
            img.thumbnail(output_size)
            img.save(self.post_image.path)

class Bookmark(models.Model):
    bookmark = models.ForeignKey(PostCreate, on_delete=models.CASCADE, related_name='bookmarks')
    user  = models.ForeignKey(User, on_delete=models.CASCADE, related_name='username_bookmark')

    def __str__(self):
        return f'{self.user} Bookmark'
    

class Notifications(models.Model):
    post_username = models.ForeignKey(User, on_delete=models.CASCADE, related_name='poster')
    user_who_like = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey(PostCreate, on_delete=models.CASCADE, related_name='post')
    date       = models.DateTimeField(default=timezone.now)

    class Meta:
        verbose_name_plural = ("Notifications")

    def __str__(self):
        return f'{self.post_username} Notification'

    def get_date(self):
        return humanize.naturaltime(self.date)

root_dir/social/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import *
from users.models import Profile
from django.forms.widgets import TextInput


class PostCreateForm(forms.ModelForm):
    post_image = forms.ImageField(label='', widget=forms.FileInput(attrs={'class':'file-upload-input', 'type':'file'}))
    class Meta:
        model = PostCreate
        fields = ['post_image']

class ProfilePictureUpdate(forms.ModelForm):
    avatar = forms.ImageField(label='', widget=forms.FileInput(attrs={'class':'profile-update-input', 'type':'file'}))
    class Meta:
        model = Profile
        fields = ['avatar',]

root_dir/social/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from .forms import PostCreateForm, ProfilePictureUpdate
from django.contrib import messages
from django.views.generic import RedirectView
from django.contrib.auth.models import User
from .models import PostCreate, Bookmark, Notifications
from users.models import Profile
from rest_framework.renderers import JSONRenderer
from django.http import HttpResponse

@login_required
def home(request):
    post = PostCreate.objects.all().order_by('-date')
    notifications = Notifications.objects.filter(post_username = request.user).order_by('-date')
    contex={
        'Posts':post,
        'notifications':notifications
    }
    return render(request, 'social/home.html', contex)


@login_required
def create(request):
    if request.method == "POST":
        form = PostCreateForm(request.POST, request.FILES)
        if form.is_valid():
            form.instance.user_name = request.user
            form.save()
            return redirect('/')
    else:
        form = PostCreateForm()
    contex = {
        'form':form
    }
    return render(request, 'social/create.html', contex)




def delete(request, id):
    obj = PostCreate.objects.get(id=id)
    if obj.user_name == request.user:
        obj.delete()
    return redirect('/')




def Like(request):
    id_ = request.POST.get("id")
    user_ = request.user
    obj = get_object_or_404(PostCreate, id=id_)
    notification = Notifications.objects.all()
    post_user = obj.user_name
    if user_.is_authenticated:
        if user_ in obj.likes.all():
            obj.likes.remove(user_)
            n = Notifications.objects.filter(post__id = obj.id)
            if n.count() > 0:
                n.delete()
        else:
            obj.likes.add(user_)
            if str(user_) != str(post_user):
                Notifications.objects.create(
                    user_who_like = user_,
                    post = obj,
                    post_username = post_user
                )
    obj_ = obj.likes.count()
    return HttpResponse(obj_)




@login_required
def bookmark(request):
    bk = Bookmark.objects.filter(user__username = request.user)
    if bk.count() > 0:
        contex = {
            'bookmarks':bk
        }
    else:
        contex = {
            'bk':"No Bookmarks To Show"
        }
    return render(request, 'social/bookmarks.html', contex)


def create_bookmark(request):
    id_ = request.POST.get("id", None)
    post = PostCreate.objects.get(id=id_)
    bk = Bookmark.objects.all()
    user = post.user_name
    delete = False
    created = False
    if bk.exists():
        bookmarks = Bookmark.objects.filter(bookmark__id = post.id)
        if bookmarks.count() > 0:
            bookmarks.delete()
            delete = True
            created = False
        else:
            Bookmark.objects.create(
                user = request.user,
                bookmark = post
            )
            created = True
    else:
        Bookmark.objects.create(
            user = request.user,
            bookmark = post
        )
        created = True

    if created:
        html = "<div class='alert alert-success alert-dismissible fade show' role='alert'>\
        <b>" + str(user) +" Post</b> Was Successfully Saved.\
        <button type='button' class='close' data-dismiss='alert' aria-label='Close'>\
        <span aria-hidden='true'>&times;</span></button></div>"
    elif delete:
        html = "<div class='alert alert-success alert-dismissible fade show' role='alert'>\
        <b>" + str(user) +" Post</b> Was Removed From Bookmarks.\
        <button type='button' class='close' data-dismiss='alert' aria-label='Close'>\
        <span aria-hidden='true'>&times;</span></button></div>"
    else:
        html = "<div class='alert alert-danger alert-dismissible fade show' role='alert'>\
         There Was An Error, Please Try Again.\
        <button type='button' class='close' data-dismiss='alert' aria-label='Close'>\
        <span aria-hidden='true'>&times;</span></button></div>"
    return HttpResponse(html)


@login_required
def profile(request, slug):
    posts = PostCreate.objects.filter(user_name__username__exact = slug).order_by('-date')
    user_ =  Profile.objects.get(user__username = slug)
    p_form = ProfilePictureUpdate()
    contex = {
        'Posts':posts,
        'user_':user_,
        'form':p_form
    }
    return render(request, 'social/profile.html', contex)

def profileChange(request):
    if request.method == "POST":
        p_form = ProfilePictureUpdate(request.POST, request.FILES, instance=request.user.profile)
        if p_form.is_valid():
            p_form.save()
            return redirect('/')
        else:
            return redirect('/')
    return redirect('/')

@login_required
def SearchAPI(request):
    search_data = request.POST.get('search_term', None)
    users =  Profile.objects.filter(user__username__contains = search_data)
    html = []
    for u in users:
        html.append(
            '<a class="card-body container-search" href="../profile/' 
            +str(u.user)+ '"><img src='+u.avatar.url+
            ' class="d-inline mr-1"><h6 class="text-left d-inline">'
            +str(u.user)+'</h6></a>')
    return HttpResponse(html)




def show_post(request, pk):
    post = PostCreate.objects.get(id = pk)
    notification = Notifications.objects.get(post__id = pk)
    notification.delete()
    contex = {
        'post':post
    }
    return render(request, 'social/show_post.html', contex)

root_dir/social/templates/social/bookmarks.html
{% extends 'social/base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="overlay"></div>
        <div class="side-menu-responsive h-100">
            <div class="menu-header mb-2">
                <div class="float-left">
                    <img src={{ user.profile.avatar.url }} class="mr-2" width="50px">
                </div>
                <div class="info">
                    <p>{{user.username}}</p>
                    <span>{{user.email}}</span>
                </div>
            </div>
            <div class="list-element">
                <a href="{% url 'social:create' %}">
                    <i class="fas fa-plus mr-2"></i>
                    <span>Create Post</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'social:bookmark' %}">
                    <i class="far fa-bookmark mr-2"></i>
                    <span>Bookmarks</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'profile' user.username %}">
                    <i class="far fa-user-circle mr-2"></i>
                    <span>Profile</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'users:settings' %}">
                    <i class="fas fa-sliders-h mr-2"></i>
                    <span>Settings</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'messenger' %}">
                    <i class="far fa-comment mr-2"></i>
                    <span>Messages</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'users:logout' %}">
                    <i class="fas fa-sign-out-alt mr-2"></i>
                    <span>Logout</span>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 d-none d-md-block">
            <div class="card">
                <div class="card-body side-menu">
                    <div class="list-element mb-4">
                        <a href="{% url 'social:bookmark' %}">
                            <i class="far fa-bookmark mr-1"></i>
                            <span>Bookmarks</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'profile' user.username %}">
                            <i class="far fa-user-circle mr-1"></i>
                            <span>Profile</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'users:settings' %}">
                            <i class="fas fa-sliders-h mr-1"></i>
                            <span>Settings</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'messenger' %}">
                            <i class="far fa-comment mr-1"></i>
                            <span>Messages</span>
                        </a>
                    </div>
                    <div class="list-element">
                        <a href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        {% if bookmarks %}
        <div class="col-lg-6 col-md-6 col-12 post-container" style="height:700px; overflow-y:scroll;">
        {% for bookmark in bookmarks %}
            <div class="card mb-3" style="padding:0;">
                <div class="card-body" style="padding:0">
                    <div class="post-info align-items-center">
                        <div class="post-image-user">
                            <img src="{{ bookmark.bookmark.user_name.profile.avatar.url }}" class="d-inline user-avatar">
                        </div>
                        <div class="info-wrapper">
                            <h6 class="text-left d-inline align-top">{{bookmark.bookmark.user_name}}</h6>
                            <span class="align-bottom time">
                            <i class="fas fa-clock"></i> {{bookmark.bookmark.get_date}}</span>
                        </div>
                    </div>
                    <div class="post">
                        <img src="{{bookmark.bookmark.post_image.url}}">
                        <i class="far fa-bookmark float-right bk" data-url={% url 'social:bookmark_create' %} data-id="{{bookmark.bookmark.id}}">
                        </i>
                    </div>
                    <div class="reactions align-items-center" data-id="{{ bookmark.bookmark.id }}" data-href="{{ bookmark.bookmark.get_like_url }}">
                        <i class="fas fa-heart mr-1"></i>
                        <span class="counter" data-id="{{ bookmark.bookmark.id }}">{{ bookmark.bookmark.likes.count }}</span>
                    </div>
                </div>
            </div>
            {% endfor %} 
        </div>
        {% else %}
        <div class="col-lg-6 col-md-6 col-12 post-container">
            <div class="card mb-3" style="padding:0;">
                <div class="card" style="padding:0">
                    <div class="card-body">
                        <p class="text-center" style="font-family: Dosis;margin-bottom: 0;font-size: 25px;">
                            {{ bk }}
                        </p>
                    </div>
                </div>
            </div>
        </div>
        {% endif %}
        <div class="blank" style="height:200px "></div>
    </div>
</div>
</div>
{% endblock %}

root_dir/social/templates/social/create.html
{% extends 'social/base.html' %} {% load crispy_forms_tags %} {% block content %}
<div class="container-fluid container-home">
    <div class="row">
        <div class="overlay"></div>
        <div class="side-menu-responsive h-100">
            <div class="menu-header mb-2">
                <div class="float-left">
                    <img src={{ user.profile.avatar.url }} class="mr-2" width="50px">
                </div>
                <div class="info">
                    <p>{{user.username}}</p>
                    <span>{{user.email}}</span>
                </div>
            </div>
            <div class="list-element">
                <a href="{% url 'social:create' %}">
                    <i class="fas fa-plus mr-2"></i>
                    <span>Create Post</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'social:bookmark' %}">
                    <i class="far fa-bookmark mr-2"></i>
                    <span>Bookmarks</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'profile' user.username %}">
                    <i class="far fa-user-circle mr-2"></i>
                    <span>Profile</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'users:settings' %}">
                    <i class="fas fa-sliders-h mr-2"></i>
                    <span>Settings</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'messenger' %}">
                    <i class="far fa-comment mr-2"></i>
                    <span>Messages</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'users:logout' %}">
                    <i class="fas fa-sign-out-alt mr-2"></i>
                    <span>Logout</span>
                </a>
            </div>
        </div>
        <div class="col-12">
            <div class="card upload-card">
                <div class="card-body" style="padding: 0;">
                    <form method="POST" class="post-form" enctype="multipart/form-data">
                        <div class="dropzone d-flex justify-content-center">
                            {% csrf_token %}
                            <label class="file-upload" for="file-upload-input">
                                Drag Your File Here Or Click To Upload
                            </label>
                            {{form|crispy}}
                            <span class="clear-files">
                                <i class="fas fa-times"></i>
                                Clear Files
                            </span>
                            <button class="clear-files" type="submit" style="left:43%;background:#007ac1;border:none">
                                <i class="fas fa-cloud-upload-alt"></i>
                                Post Image
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
{% endblock %}

root_dir/social/templates/social/home.html
{% extends 'social/base.html' %} {% block content %}
<div class="container-fluid container-home">
    <div class="row">
        <div class="overlay"></div>
        <div class="side-menu-responsive h-100">
            <div class="menu-header mb-2">
                <div class="float-left">
                    <img src={{ user.profile.avatar.url }} class="mr-2" width="50px">
                </div>
                <div class="info">
                    <p>{{user.username}}</p>
                    <span>{{user.email}}</span>
                </div>
            </div>
            <div class="list-element">
                <a href="{% url 'social:create' %}">
                    <i class="fas fa-plus mr-2"></i>
                    <span>Create Post</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'social:bookmark' %}">
                    <i class="far fa-bookmark mr-2"></i>
                    <span>Bookmarks</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'profile' user.username %}">
                    <i class="far fa-user-circle mr-2"></i>
                    <span>Profile</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'users:settings' %}">
                    <i class="fas fa-sliders-h mr-2"></i>
                    <span>Settings</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'messenger' %}">
                    <i class="far fa-comment mr-2"></i>
                    <span>Messages</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'users:logout' %}">
                    <i class="fas fa-sign-out-alt mr-2"></i>
                    <span>Logout</span>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 d-none d-md-block">
            <div class="card">
                <div class="card-body side-menu">
                    <div class="list-element mb-4">
                        <a href="{% url 'social:bookmark' %}">
                            <i class="far fa-bookmark mr-1"></i>
                            <span>Bookmarks</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'profile' user.username %}">
                            <i class="far fa-user-circle mr-1"></i>
                            <span>Profile</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'users:settings' %}">
                            <i class="fas fa-sliders-h mr-1"></i>
                            <span>Settings</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'messenger' %}">
                            <i class="far fa-comment mr-1"></i>
                            <span>Messages</span>
                        </a>
                    </div>
                    <div class="list-element">
                        <a href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-12 post-container" style="height:700px; overflow-y:scroll;">
            {% for post in Posts %}
            <div class="card mb-3" style="padding:0;">
                <div class="card-body" style="padding:0">
                    <div class="post-info align-items-center">
                        <div class="post-image-user">
                            <img src="{{ post.user_name.profile.avatar.url }}" class="d-inline">
                        </div>
                        <div class="info-wrapper">
                            <a class="text-left d-inline align-top" href="{% url 'profile' post.user_name %}">{{post.user_name}}</a>
                            <span class="align-bottom time">
                            <i class="fas fa-clock"></i> {{post.get_date}}</span>
                        </div>
                        <div class="actions">
                            {% if user.username|slugify == post.user_name|slugify %}
                            <a data-url="{% url 'social:delete' post.id %}" data-toggle="tooltip" data-placement="bottom" title="Delete Post Permanently?"><i class="fas fa-trash-alt"></i></a> {% endif %}
                        </div>
                    </div>
                    <div class="post">
                        <img src="{{post.post_image.url}}" width="100%"> {% if user.username|slugify != post.user_name|slugify %}
                        <i class="far fa-bookmark float-right bk" data-url={% url 'social:bookmark_create' %} data-id="{{post.id}}">
                            </i> {% endif %}
                    </div>
                    <div class="reactions align-items-center" data-id="{{ post.id }}" data-href="{{ post.get_like_url }}">
                        <i class="fas fa-heart mr-1"></i>
                        <span class="counter" data-id="{{ post.id }}">{{ post.likes.count }}</span>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="blank" style="height:200px "></div>
        </div>
    </div>
</div>
{% endblock %}

root_dir/social/templates/social/show_post.html
{% extends 'social/base.html' %}
{% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="overlay"></div>
        <div class="side-menu-responsive h-100">
            <div class="menu-header mb-2">
                <div class="float-left">
                    <img src={{ user.profile.avatar.url }} class="mr-2" width="50px">
                </div>
                <div>
                    <p>{{user.username}}</p>
                    <span>{{user.email}}</span>
                </div>
            </div>
            <div class="list-element">
                <a href="{% url 'social:create' %}">
                    <i class="fas fa-plus mr-2"></i>
                    <span>Create Post</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'social:bookmark' %}">
                    <i class="far fa-bookmark mr-2"></i>
                    <span>Bookmarks</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'profile' user.username %}">
                    <i class="far fa-user-circle mr-2"></i>
                    <span>Profile</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'users:settings' %}">
                    <i class="fas fa-sliders-h mr-2"></i>
                    <span>Settings</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'messenger' %}">
                    <i class="far fa-comment mr-2"></i>
                    <span>Messages</span>
                </a>
            </div>
            <div class="list-element">
                <a href="{% url 'users:logout' %}">
                    <i class="fas fa-sign-out-alt mr-2"></i>
                    <span>Logout</span>
                </a>
            </div>
        </div>
        <div class="col-lg-3 col-md-3 d-none d-md-block">
            <div class="card">
                <div class="card-body side-menu">
                    <div class="list-element mb-4">
                        <a href="{% url 'social:bookmark' %}">
                            <i class="far fa-bookmark mr-1"></i>
                            <span>Bookmarks</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'profile' user.username %}">
                            <i class="far fa-user-circle mr-1"></i>
                            <span>Profile</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'users:settings' %}">
                            <i class="fas fa-sliders-h mr-1"></i>
                            <span>Settings</span>
                        </a>
                    </div>
                    <div class="list-element mb-4">
                        <a href="{% url 'messenger' %}">
                            <i class="far fa-comment mr-1"></i>
                            <span>Messages</span>
                        </a>
                    </div>
                    <div class="list-element">
                        <a href="{% url 'users:logout' %}">
                            <i class="fas fa-sign-out-alt"></i>
                            <span>Logout</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6 col-md-6 col-12 post-container" style="height:700px; overflow-y:scroll;">
            <div class="card mb-3" style="padding:0;">
                <div class="card-body" style="padding:0">
                    <div class="post-info align-items-center">
                        <div class="post-image-user">
                            <img src="{{ post.user_name.profile.avatar.url }}" class="d-inline">
                        </div>
                        <div class="info-wrapper">
                            <a class="text-left d-inline align-top" href="{% url 'profile' post.user_name %}">{{post.user_name}}</a>
                            <span class="align-bottom time">
                            <i class="fas fa-clock"></i> {{post.get_date}}</span>
                        </div>
                        <div class="actions">
                            {% if user.username|slugify == post.user_name|slugify %}
                            <a data-url="{% url 'social:delete' post.id %}" data-toggle="tooltip" data-placement="bottom" title="Delete Post Permanently?"><i class="fas fa-trash-alt"></i></a> {% endif %}
                        </div>
                    </div>
                    <div class="post">
                        <img src="{{post.post_image.url}}" width="100%"> {% if user.username|slugify != post.user_name|slugify %}
                        <i class="far fa-bookmark float-right bk" data-url={% url 'social:bookmark_create' %} data-id="{{post.id}}">
                            </i> {% endif %}
                    </div>
                    <div class="reactions align-items-center" data-id="{{ post.id }}" data-href="{{ post.get_like_url }}">
                        <i class="fas fa-heart mr-1"></i>
                        <span class="counter" data-id="{{ post.id }}">{{ post.likes.count }}</span>
                    </div>
                </div>
            </div>
            <div class="blank" style="height:200px "></div>
        </div>
    </div>
</div>
{% endblock  %}