root_dir/root/urls.py
from django.contrib import admin
from django.urls import path, include
from social.views import profile, profileChange
from imessage.views import messanger_home, messanger_create, messanger_show
urlpatterns = [
    path('', include('users.urls')),
    path('profile/<str:slug>/', profile, name="profile"),
    path('profileChange/', profileChange, name="profile-change"),
    path('imessage/', messanger_home, name="messenger"),
    path('send_imessage/', messanger_create, name="messanger_create"),
    path('chat/', messanger_show, name="messanger_create"),
    path('home/', include('social.urls'), name="home"),
    path('admin/', admin.site.urls),
]

root_dir/social/urls.py
from django.urls import path
from .views import *


app_name = 'social'
urlpatterns = [
    path('', home, name='home'),
    path('create/', create, name='create'),
    path('post/<int:pk>', show_post, name="show_post"),
    path('search/', SearchAPI, name='search'),
    path('like/', Like, name='Like-toggle'),
    path('bookmark/', create_bookmark, name='bookmark_create'),
    path('delete/<int:id>', delete, name='delete'),
    path('bookmarks/', bookmark, name='bookmark'),
]

root_dir/imessage/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.core.exceptions import ValidationError


class imessage (models.Model):    
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name="sender")
    reciever = models.ForeignKey(User, on_delete=models.CASCADE, related_name="reciever")
    date = models.DateTimeField(default=timezone.now)
    message = models.TextField(max_length=300)

    class Meta:
        verbose_name = ("Imessage")

    def __str__(self):
        return f'{self.reciever} Message'

root_dir/imessage/forms.py
from django import forms
from .models import *

class MessageVerfication(forms.ModelForm):
    message = forms.CharField(label='', required=True, widget=forms.TextInput(attrs={'placeholder':'Type a message', 'class':'msg-input'}))
    class Meta:
        model = imessage
        fields = ['message']

root_dir/imessage/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, JsonResponse
from django.core import serializers
from django.contrib.auth.models import User
from django.utils import timezone
from users.models import Profile
from .models import imessage
from django.db.models import Q
from .forms import MessageVerfication
from asgiref.sync import async_to_sync
from channels.layers import get_channel_layer
from django.db.models import Count


def messanger_home(request):
    form = MessageVerfication()
    users = Profile.objects.exclude(user__username = request.user)
    messages = imessage.objects.filter(sender = request.user)

    duplicates_messages = imessage.objects.filter(sender__username = request.user).values('reciever_id', "message").order_by('-date').distinct()
    result = []
    seen = []
    for data in range(len(duplicates_messages)):
        if duplicates_messages[data]['reciever_id'] not in seen:
            seen.append(duplicates_messages[data]['reciever_id'])
            result.append(duplicates_messages[data])
        
    contex = {
        "users_data":users,
        "form":form,
        "last_messages":result,
    }
    return render(request, 'imessage/home.html', contex)

def messanger_create(request):
    reciever = request.POST.get("reciever", None)
    message = request.POST.get("message", None)
    user = User.objects.get(id = reciever)
    html = []
    form = MessageVerfication(request.POST)
    if form.is_valid():    
        obj = imessage.objects.create(
            sender = request.user,
            reciever = user,
            message = message,
            date = timezone.now()
        )
        event_triger(reciever, message, request.user.id)
        msg = imessage.objects.values().filter(reciever__id = reciever, sender__username = request.user).order_by('-date')[:1]
        html.append("<div class='container-message d-flex justify-content-end float-right'>\
                        <p class='text-right mr-3 align-self-center'>"+ msg[0]['message'] +"</p>\
                    </div>")
        return HttpResponse(html)
    else:
        errors = {
            "status": 505,
            "Error": "Message Is Require"
        }
        return JsonResponse(errors)

def messanger_show(request):
    reciever_ = request.POST.get("reciever", None)
    user = request.POST.get("user", None)
    html = []
    if int(user) == int(request.user.id):
        messages = imessage.objects.values().filter(Q(reciever__id = reciever_, sender__id = user) | Q(reciever__id = user, sender__id = reciever_)).order_by('date')
        for mesg in range(len(messages)):
            if int(messages[mesg]['sender_id']) == int(request.user.id):
                html.append("<div class='container-message d-flex justify-content-end float-right'>\
                                <p class='text-right mr-3 align-self-center'>"+ messages[mesg]['message'] +"</p>\
                            </div>")
            else:
                html.append("<div class='container-message float-left'>\
                                <p class='text-left reciever ml-3'>"+ messages[mesg]['message'] +"</p>\
                            </div>")
    else:
        html = "ERROR"
    return JsonResponse({
        "html":html,
        "user":str(reciever_)
    })




def event_triger(user, message, loged_in_user):
    send_msg = "<div class='container-message float-left'><p class='text-left reciever ml-3'>"+ message +"</p></div>"
    channel_layer = get_channel_layer()
    async_to_sync(channel_layer.group_send)(
        str(user)+'_room',
        {
            'type': 'send_message_to_frontend',
            'message': send_msg,
            'id':str(loged_in_user)
        }
    )

root_dir/imessage/templates/imessage/base.html
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/css/messages.css?{% now 'U' %}">
    <title>Imessage</title>
  </head>
  <body>
  {% if user.is_authenticated %}
    <nav class="navbar navbar-light navbar-expand-md justify-content-center mb-3" style="background:white">
    <div class="container-fluid">
      <a href="{% url 'social:home' %}" class="brand d-flex w-100 mr-auto">Social+ <span class="mr-2 ml-2" style="font-size:25px">/</span> Imessage </a>
      <img src={{user.profile.avatar.url}} width="35px" class="mr-2 profile" style="border-radius: 100%;">
      <div class="navbar-collapse collapse w-100" id="collapsingNavbar3">
      </div>
      </div>
    </nav>
  {% endif %}

    {% block content %}
    {% endblock  %}
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <script src="https://kit.fontawesome.com/97de7561e9.js" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
    

    {% load static %}
    <script src="{% static '/js/websocketbridge.js' %}" type="text/javascript"></script>
    <script src="{% static '/js/node_modules/js-cookie/src/js.cookie.js' %}"></script>
    <script src="/static/Js/mainScript.js?{% now 'U' %}"></script>
  </body>
</html>

root_dir/imessage/templates/imessage/home.html
{% extends 'imessage/base.html' %} {% block content %}
<div class="container-fluid">
    <div class="row">
        <div class="col-12 d-block d-md-none">
            <div class="card uper-users-panel">
                <div class="card-body d-flex" style="padding:13px">
                    {% for u in users_data %}
                    <div class="uper-msg-head" data-id="{{ u.user.id }}" data-user="{{ user.id }}">
                        <img src={{ u.avatar.url }} class="mr-4">
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
        <div class="col-lg-4 col-md-4 d-none d-md-block">
            <div class="card">
                <div class="card-body">
                    <div class="container-msges-contacts">
                    {% for u in users_data %}
                            <div class="msg-head mb-2 " data-id="{{ u.user.id }}" data-user="{{ user.id }}">
                                <div class="user-profile mr-2 float-left">
                                    <img src={{ u.avatar.url }} width="40px">
                                </div>
                                <div class="message-info" style="position: relative;top: -3px;">
                                    <p class="align-middle">{{ u.user }}</p>
                                    {% load filter %}
                                    {% if last_messages|hash:u.user.id != None %}
                                        <p class="latest-message">{{ last_messages|hash:u.user.id }}</p>
                                    {% else %}
                                        <p class="latest-message">No Recent Messages Yet</p>
                                    {% endif %}
                                </div>
                            </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-8 col-md-8 col-12">
            <div class="card">
                <div class="msg">
                </div>
                <div class="message-form">
                    {{form}}
                    <button type="submit" class="send"><i class="fas fa-paper-plane"></i></button>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}